### ISSUE TITLE
Save graphs in text format

### ISSUE THREAD

**Issue by andreiolaru-ro** [andreiolaru-ro/AmIciTy-Grph#11]
* graphs can be loaded and saved in text form
 * see net.xqhs.graphs.examples.SimpleGraphUsageExamples (uses TextGraphRepresentation)
 * save and read layout using the graph description (see net.xqhs.graphs.graph.Graph)
  * [x] reading and writing of the description tested in #10 
  * [x] extend GraphDescription with a class that contains the graph layout and can read/write it
  * [x] in the description, at first the layout and other parameters may be just serialized (serialize to a ByteOutputStream or smth)
  * [x] then, there will be a text format for them

**Comment by catalinb** [comment]
Fixed unique identifier issue but the indexes are not reconstructed in the same order.

**Comment by andreiolaru-ro** [comment]
* reconstruct by using NodeP.genericIndex()

**Comment by andreiolaru-ro** [comment]
Apparently fixed in a82131aa2a180fb47996ef2b3e21b4c399d2d793
