### ISSUE TITLE
Nodes with the same name should not be allowed

### ISSUE THREAD

**Issue by andreiolaru-ro** [andreiolaru-ro/AmIciTy-Grph#14]
* [x] when renaming a node, a name that already exists should not be allowed
* [x] when creating a node, it should be checked if a node with the same name exists
 * if it does, see if the existing name has a number at the end
  * if it has, increment the number for the new node
  * if it doesn't, add '2' at the end of the name 
  * in both cases, if the name already exists, increment the number again, and so on

**Comment by catalinb** [comment]
Fixed in b5ab187b2418756ad9623a5bb42ecd26319538a0
