### ISSUE TITLE
Newly created graphs/patterns should have unique names

### ISSUE THREAD

**Issue by catalinb** [andreiolaru-ro/AmIciTy-Grph#20]
There are currently two outstanding problems when saving/loading a graph library.

1. Parsing the metadata file may fail if two graphs/nodes have the same name
2. Files may be overwritten when saving a library containing patterns/graphs with the same name

**Comment by andreiolaru-ro** [comment]
* [ ] when saving, if there are graphs / patterns with the same name (at least one pair), display an alert and don't allow save.

**Comment by andreiolaru-ro** [comment]
Solved in commit 820a8fabc1af04af481ebf5a46bcccd3918c807f
