### ISSUE TITLE
Start working with datasets

### ISSUE THREAD

**Issue by andreiolaru-ro** [andreiolaru-ro/AmIciTy-Grph#25]
* [ ] process datasets
  * without it taking forever
* [ ] easily switch (at compile-time) between what dataset is used
  * custom dataset parsing classes?

* datasets:
  * ARAS -- quite large, annotated, many types of sensors http://cmpe.boun.edu.tr/aras/
  * CASAS -- Kyoto 3 and 4 http://ailab.wsu.edu/casas/datasets/
    * large, multi-resident, many files, focused on presence, annotated
    * also dataset 11 -- large file, annotated
  * MERLSense (Mitsubishi) https://sites.google.com/a/drwren.com/wmd
    * very large

**Comment by andreiolaru-ro** [comment]
Papers to read:
  * K. Cook and L. Holder. Automated activity-aware prompting for activity initiation. Gerontechnology, 11(4):1-11, 2013;
  * M. Krishnan and D. Cook. Activity recognition on streaming sensor data. Pervasive and Mobile Computing, 20:138-154, 2014

Găsești lucrările echipei lui Diane Cook pe site-ul ei http://www.eecs.wsu.edu/~cook/pubs.html

**Comment by catalinb** [comment]
TODO:
* [ ] In memory representation of datasets
* [ ] Aggregate data from multiple files
* [ ] Lookup by time and date, sensor id
* [ ] Look for visualization options

**Comment by andreiolaru-ro** [comment]
Closing issue indefinitely.
